[package]
name = "wines"
version = "0.1.0"
authors = ["jp <fiorini751@gmail.com>"]

[dependencies]
actix-web = "0.7"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
select = "0.4.2"
reqwest = "0.9.2"
